"use client"

// import type { Metadata } from "next";
import React, { useState, useEffect} from "react";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";





// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

interface Global {
  favicon?: string;
}

interface PageData {
  favicon?: Global;
  // Add other sections if needed
}
export default function RootLayout({

  
  children,
  
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [data, setData] = useState<PageData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  
    useEffect(() => {
      const fetchData = async () => {
        try {
          const response = await fetch('https://batchatv.clickysoft.us/wp-json/wp/v1/options');
          if (!response.ok) {
            throw new Error('Network response was not ok');
          }
          const result: PageData = await response.json();
          setData(result);
        } catch (err) {
          setError(err instanceof Error ? err.message : 'An unknown error occurred');
        } finally {
          setLoading(false);
        }
      };
  
      fetchData();
    }, []);
    // console.log(data?.favicon);
  return (
    <html lang="en">

      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {data?.favicon && (
          <link rel="icon" href={data.favicon} />
        )}
        
      </head>
      <body
        className="antialiased"
        suppressHydrationWarning
      >

        {children}
      </body>
    </html>
  );
}
